### PR TITLE
Relax scope of some CloudWatch logging permissions

### PR DESCRIPTION
**Pull request by aviflax**
Ran into some trouble with this; this change helped and seems mostly
harmless.

### CODE REVIEW

**Review by levand — APPROVED** [review]

**Comment by aviflax** [comment]
Ah, I guess I should have bumped the version in `package.json` before merging this… I should open up a follow-up PR, right? Is there anything else I’d need to do? Publish to npm?

**Comment by levand** [comment]
Yes, correct procedure is to bump the version number then deploy to NPM.

You'll need me to add your NPM account as a collaborator to give you push permissions (unless it's smart enough to use the Github SSO to figure out you're already a collaborator.)

**Comment by aviflax** [comment]
OK, I’ll give it a try and let you know. Thanks!

**Comment by aviflax** [comment]
Ah, never mind, looks like you took care of it.

**Pull request merged**
